### ISSUE TITLE
Getting issue for cdn

### ISSUE THREAD

**Issue by ketanrana2001** [jcoleman-pcprofessional/True-Script-Editor#7]
We have installed web part in 2018 and now we are getting below error on page
[SPLoaderError.loadComponentError]:
Failed to load component "5b3ca4ee-a6df-493d-bd4f-8489a5b246a2" (TrueScriptEditorWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/pcpro365.sharepoint.com/163800463de5f9285ad4f6f9cc0a97985b96b057e062d4733849cc0fc90eeffbd6d72bb8/TrueScriptEditor/true-script-editor-truescripteditorstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'trueScriptEditorStrings' in component '5b3ca4ee-a6df-493d-bd4f-8489a5b246a2' (TrueScriptEditorWebPart). There was an error requesting the file.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/pcpro365.sharepoint.com/163800463de5f9285ad4f6f9cc0a97985b96b057e062d4733849cc0fc90eeffbd6d72bb8/TrueScriptEditor/true-script-editor-truescripteditorstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'trueScriptEditorStrings' in component '5b3ca4ee-a6df-493d-bd4f-8489a5b246a2' (TrueScriptEditorWebPart). There was an error requesting the file.
CALLSTACK:
Error
    at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_e216f9d2ceba19eb89f0f03a7b3d7c7b.js:67:19823)
    at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_e216f9d2ceba19eb89f0f03a7b3d7c7b.js:68:9374)
    at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_e216f9d2ceba19eb89f0f03a7b3d7c7b.js:68:46574)
    at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_e216f9d2ceba19eb89f0f03a7b3d7c7b.js:68:42619)
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_5fb53ed0cfeca06f5fdc.js:1:66020

**Comment by HeikoWatz** [comment]
We experience the same problem, and we need a solution for this as soon as possible. Thank You.
Pleas help!
